### ISSUE TITLE
FetchError when doing leftJoin from public to a defined schema

### ISSUE THREAD

**Issue by boh1996** [knorm/relations#66]
When doing a leftJoin from public to a table with schema, Knorm produces the following query part:
```
LEFT JOIN "governance"."module" AS "governance"."module_1" ON "governance"."module_1"."identifier" = "entity_config"."module_identifier"
```
The error message returned from the database is `EntityConfig: syntax error at or near "."`, using the SQL query position returned yields that the `.` it is complaining about is the one in the AS part. 
`"governance"."module_1"` if the alias is changed to `"governance.module_1"` then it works fine.

**Comment by joelmukuthu** [comment]
Hmm, I think the bug comes from here https://github.com/knorm/knorm/blob/c546483454da73989bb92bf7f9d0546d7ae694f4/lib/Query.js#L297. The alias is formatted as a table-name. PR? :)

**Comment by boh1996** [comment]
Alright, will try to implement a solution cleaner than the hack i tested while debugging - and then open a PR :)

**Comment by boh1996** [comment]
Hey @joelmukuthu!

Tried to play around with changing the alias formatting, but other errors started to occur with unnamed FROM etc. So i do not think i have enough knowledge about Knorm+Relations to fix it :i
